### ISSUE TITLE
Left blank margin increase

### ISSUE THREAD

**Issue by rafi** [lambdalisue/fern-renderer-nerdfont.vim#1]
The left margin is 2 blank characters without this plugin,
but when installing fern-renderer-nerdfont plugin - it is 3 blank characters!

It's too wide :)

(defx on top, fern bottom)
![image](https://user-images.githubusercontent.com/147918/88712544-8e04e480-d122-11ea-8b4c-78e6f911df9f.png)

**Comment by lambdalisue** [comment]
Fixed. Thanks 👍
