### ISSUE TITLE
Indentation guides

### ISSUE THREAD

**Issue by wolfisdev** [lambdalisue/fern-renderer-nerdfont.vim#10]
Is it possible to add indentation guides to make it more obvious which folder a file belongs to?

Or alternatively increase the indentation size?

Thanks.

**Comment by lambdalisue** [comment]
I'm sorry for the late reply. https://github.com/lambdalisue/fern-renderer-nerdfont.vim/blob/master/doc/fern-renderer-nerdfont.txt#L35 may help you.

**Comment by lambdalisue** [comment]
Closed by #20
