### ISSUE TITLE
Not able to keep file in focus with reveal

### ISSUE THREAD

**Issue by tinny-blueleo** [lambdalisue/fern-renderer-nerdfont.vim#13]
Hey friends!

I'm unable to keep a file in focus in the drawer when I switch between different buffers.  This is my current setup:

	  vim.cmd([[
	  	if !isdirectory(expand('%:p'))
			augroup fern-startup
				autocmd! *
			augroup END
		else 
			augroup fern-startup
				autocmd! *
				autocmd VimEnter * ++nested Fern <afile> -drawer -reveal=% -stay
				autocmd BufRead * ++nested Fern . -drawer -reveal=% -stay
			augroup END
		endif
	  ]])

It only focuses on the file when it's a new file being added to the buffer but doesn't switch focus if I'm switching back to a file in the window that's already in the buffer.

**Comment by lambdalisue** [comment]
1. You are in the wrong repository. Create a new issue on https://github.com/lambdalisue/fern.vim
2. Actually, I don't get your question. What is your expected behavior and what is current actual behavior?
