### ISSUE TITLE
How to install this? No icons in tree no matter what I do.

### ISSUE THREAD

**Issue by idchlife** [lambdalisue/fern-renderer-nerdfont.vim#15]
I'm using Termux on Android. I installed custom Fira Code NerdFont font fot it.
After that I installed devicons plugin for vim and my vimairline plugin used it as integration and I got pretty icons for my system (proot debian) and filetypes in the vimairline.

BUT no matter what I do I dont have any kind of icons in fern:

![image](https://user-images.githubusercontent.com/4563032/166924010-e3c78263-8d00-4964-a2d7-3015a0a495c3.png)

I tried renderer in .vimrc "nerdtree" and "devicons" 

I tried copying files from "autoload" dir into my ~/.vim/plugged and my ~/.vim/autoload folders - no luck.

I mean I can and I use function from "nerdtree" plugin to check which icon for which file/folder, but no luck with icons for fern tree so far...

**Comment by lambdalisue** [comment]
Did you install https://github.com/lambdalisue/nerdfont.vim?

**Comment by idchlife** [comment]
> Did you install https://github.com/lambdalisue/nerdfont.vim?

Yes, I installed it. Function works in vim for folders etc. I installed it copying the plugin folder into /autoload and /plugged since I did not find the way to install it with vim-plug 🤷🏻 

Anyway, nerdfont functions work. 

But still no icons in fern, unfortunately @lambdalisue

**Comment by lambdalisue** [comment]
Where did you put `let g:fern#renderer = "nerdfont"`? I found that your screenshot uses `|+` things so it seems fern does not recognize renderer.

**Comment by idchlife** [comment]
@lambdalisue I put it inside .vimrc:

![image](https://user-images.githubusercontent.com/4563032/169892712-6a035b11-c919-4e49-9283-9a59755dc7ca.png)

**Comment by lambdalisue** [comment]
Sorry for late reply. Well, I've no idea why your `.vimrc` has some [fern codes](https://github.com/lambdalisue/fern-renderer-nerdfont.vim/blob/5939050ed74cdb9ffea6bc75ab17d146a0db7ca5/plugin/fern_renderer_nerdfont.vim#L1-L8) .... Well, I'm sorry but it seems you mis-understand some basics of installing Vim plugins I guess. Probably the best place to ask this question is StackOverflow or vim-plug issue itself.

**Comment by idchlife** [comment]
@lambdalisue I tried inserting them trying to figure out why nerdfont wont work. Unfortunately, it does not work to this day. Nerdfont works in my terminal window but not in vim with fern nerdfont.

I wrote how I tried installing this plugin in my previous messages, if you insist this is the wrong way of installation of the plugin I think it would be better to close the issue since yes I guess I made some mistakes in installation process...

**Comment by lambdalisue** [comment]
How to install is kindas related to the plugin so I can help at least you provides me the following information

1. Vim/Neovim version
2. Terminal name and version
3. Minimal vimrc (Read https://github.com/lambdalisue/fern.vim/wiki/Minimal-vimrc first)
4. Minimal step to reproduce

**Comment by idchlife** [comment]
@lambdalisue a lot of time passed since I started this issue and I tried to recreate the whole setup again and I suspect that I can't understand the installation process of nerdfont, fern-renderer-nerdfont. For some reason on my termux setup the copying of nerdfont plugin into /plugged folder worked but on my macos machine with iterm it does not.

Those files has .vim extension and folder with them. Can I ask you - what is the proper way of installing nerdfont vim plugin and this particular plugin?
I am using vim-plug plugin manager and I never installed plugins by hand. I suspect this is the case and I guess... I should like create manually ~/.vim/plugin folder and put plugins there or something? (tried that got a lot of syntax errors though)

That is the main reason I got confused, since I usually encountered vim plugins having the "installation" section with like "just use pathogen/vim-plug etc with this plugin name".
Sorry for being such newcomer to the vim plugin ecosystem, but this is honestly the first time I try installing plugins by hand avoiding the plugin managers.

**Comment by lambdalisue** [comment]
1. Make sure that one of [Nerd Fonts](https://www.nerdfonts.com/) is used in your terminal
2. Add `Plug 'lambdalisue/nerdfont.vim'` on your `.vimrc` and install the plugin (`:PlugInstall` I guess)
3. Confirm if the nerdfont.vim is installed properly by `echo nerdfont#find()`
4. Add `Plug 'lambdalisue/fern-renderer-nerdfont.vim'` on your `.vimrc` and install the plugin
5. Confirm if the fern-renderer-nerdfont.vim is installed properly by `echo fern#renderer#nerdfont#new()`
6. Add `let g:fern#renderer = "nerdfont"` on your `.vimrc`

**Comment by idchlife** [comment]
@lambdalisue thank you very much. This solved everything. I used to finding plugin "paths" for installation via README or via vimawesome website. I did not know the base way of installing is writing username/plugin.vim for github repositories.

Thank you!
