### ISSUE TITLE
gives error when starting

### ISSUE THREAD

**Issue by Cris-lml007** [lambdalisue/fern-renderer-nerdfont.vim#17]
gives me these errors when starting neovim
`E121: Undefined variable: g:fern#renderers`
`E116: Argumentos inválidos para la función: extend`

**Comment by lambdalisue** [comment]
I've never seen such errors. Give me 1) Your environment informations, 2) Minimal vimrc (See https://github.com/lambdalisue/fern.vim/wiki/Minimal-vimrc)
