### ISSUE TITLE
Startup errors on low vim version (nvim is fine)

### ISSUE THREAD

**Issue by kurkale6ka** [lambdalisue/fern-renderer-nerdfont.vim#18]
I get the following errors despite `let g:fern_disable_startup_warnings = 1`.
Other _fern_ plugins are fine (highjack, nerdfont, palette).

```
Error detected while processing .../vim/plugged/fern.vim/autoload/fern.vim:
line    5:
E492: Not an editor command: const g:fern#STATUS_NONE = 0
line    6:
E492: Not an editor command: const g:fern#STATUS_COLLAPSED = 1
line    7:
E492: Not an editor command: const g:fern#STATUS_EXPANDED = 2
line    9:
E492: Not an editor command: const g:fern#DEBUG = 0
line   10:
E492: Not an editor command: const g:fern#INFO = 1
line   11:
E492: Not an editor command: const g:fern#WARN = 2
line   12:
E492: Not an editor command: const g:fern#ERROR = 3
line   46:
E121: Undefined variable: g:fern#INFO
E116: Invalid arguments for function <SNR>42_config
Error detected while processing .../vim/plugged/fern-renderer-nerdfont.vim/plugin/fern_renderer_nerdfont.vim:
line    8:
E121: Undefined variable: g:fern#renderers
E116: Invalid arguments for function extend
Press ENTER or type command to continue
```

**Comment by lambdalisue** [comment]
low is?

**Comment by kurkale6ka** [comment]
```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jun 14 2022 02:52:30)
Included patches: 1-1763
```

**Comment by lambdalisue** [comment]
![CleanShot 2022-09-14 at 20 03 58](https://user-images.githubusercontent.com/546312/190137553-73fd4347-887e-47c0-a7c1-cb1ceefaef88.png)

I'm sorry but fern does not support that Vim. Supported version is 8.1.2269 or later

**Comment by kurkale6ka** [comment]
I am aware of this, else I wouldn't have mentioned the `let g:fern_disable_startup_warnings = 1` variable:
```
[fern] Vim prior to 8.1.0994 does not have required feature thus fern is disabled.
[fern] Disable this warning message by adding "let g:fern_disable_startup_warnings = 1" on your vimrc.
```
but once this variable is set there are no error messages so I presume you must be doing a `has("patch-8.1.2269")` test for the other plugins I talked about.
I can do this test in my `.vimrc` but it's maybe best to do it within the plugin same as for the other ones.

**Comment by lambdalisue** [comment]
Configuration with `let g:fern_disable_startup_warnings = 1` is not supported.

> I can do this test in my .vimrc but it's maybe best to do it within the plugin same as for the other ones.

You need to do that because you are using unsupported Vim by your choise.
