### ISSUE TITLE
Add options for paddings (spaces) around symbols (icons) of leaves/branches

### ISSUE THREAD

**Issue by creativenull** [lambdalisue/fern-renderer-nerdfont.vim#21]
As the title says, I see there is no spacing between the root folders and the sign column/line numbers. Here is a screenshot:

<img width="212" alt="Screenshot 2022-10-24 at 14 16 21" src="https://user-images.githubusercontent.com/3767728/197596867-789be6bc-7d83-41d0-a6e4-ff1cc538fede.png">

Is there any way to add some padding before it?

**Comment by lambdalisue** [comment]
Unfortunately no.

**Comment by creativenull** [comment]
Hmmm I see, I saw that the default renderer had a symbol prefix to the root folder so I thought it would've been possible to replace that with a space instead on the nerdfont renderer, showing the default renderer at the image below.

![image](https://user-images.githubusercontent.com/3767728/198654531-ca953b42-2cdf-4c32-9f45-ffb88cceaad6.png)

I'm sorry if this would be the wrong place to have this feature for fern, but if there is a way to do this.

**Comment by lambdalisue** [comment]
I'm sorry but I think I don't get the situation. Could you explain your situation and want more clearly?

**Comment by creativenull** [comment]
Sorry if I wasn't clear, but what I wanted was some padding between files/folders when I view them.

So basically a way to change how it would look like, if this is not a feature that can be done then that's fine as well, I could look into the code and see what I could do to get those padding, no worries :)

For example for the default renderer, this is what I have:

```vim
let g:fern#renderer#default#root_symbol = ' @@ '
let g:fern#renderer#default#leaf_symbol = ' '
let g:fern#renderer#default#collapsed_symbol = ' + '
let g:fern#renderer#default#expanded_symbol = ' - '
let g:fern#renderer#default#leading = '  '
```

And here is how it looks, note the space before the `+` is what I want:

![image](https://user-images.githubusercontent.com/3767728/198847604-764c5d61-44ce-4ba0-ace9-1406ab8f36c1.png)

But I cannot do this with the nerdfont renderer because it doesn't have variables for `leaf`, `collapsed` and `expanded` symbols where I could add some spacing.

Edit: space before `+` not after

**Comment by lambdalisue** [comment]
Thanks. Now I got :+1:

Well, it's not possible with the current implementation but PR is welcome 👍 

https://github.com/lambdalisue/fern-renderer-nerdfont.vim/blob/master/autoload/fern/renderer/nerdfont.vim#L99
https://github.com/lambdalisue/fern-renderer-nerdfont.vim/blob/master/autoload/fern/renderer/nerdfont.vim#L123
