### ISSUE TITLE
Some Icons are Showing, Some Aren't

### ISSUE THREAD

**Issue by cickes** [lambdalisue/fern-renderer-nerdfont.vim#22]
Using 
```
Plug 'lambdalisue/nerdfont.vim'
Plug 'lambdalisue/fern-renderer-nerdfont.vim'
Plug 'lambdalisue/glyph-palette.vim'
```
Some glyphs will load.  Most show the font characters.  
![image](https://user-images.githubusercontent.com/4763755/197603332-0df26be3-45f4-4f13-a1ca-0bcb48f7a118.png)

In `.vimrc`  
```
augroup my-glyph-palette
  autocmd! *
  autocmd FileType fern call glyph_palette#apply()
  autocmd FileType nerdtree,startify call glyph_palette#apply()
augroup END
let g:fern#renderer = "nerdfont"
```

**Comment by lambdalisue** [comment]
Probably, your nerdfont is old and does not support that character. Which nerdfont and version do you use?

**Comment by cickes** [comment]
Correct.  Updated nerd font solved the issue.
