### ISSUE TITLE
Vue icon is broken

### ISSUE THREAD

**Issue by timsofteng** [lambdalisue/fern-renderer-nerdfont.vim#4]
Hey. Vue icon is broken. However it works in airline.
![image](https://user-images.githubusercontent.com/51912173/90002122-eb5c7200-dc9a-11ea-8fe5-144bd0566c39.png)

vim
st-terminal
freebsd

**Comment by lambdalisue** [comment]
Prob. an issue on https://github.com/lambdalisue/nerdfont.vim
So please create it there.

**Comment by timsofteng** [comment]
@lambdalisue done

**Comment by lambdalisue** [comment]
https://github.com/lambdalisue/nerdfont.vim/issues/3
