### ISSUE TITLE
Vim freezes

### ISSUE THREAD

**Issue by Igor-Gold** [lambdalisue/fern-renderer-nerdfont.vim#5]
This issue is reproducible, and I've isolated it to this module.

These are my settings which are enough to cause a freeze/crash:

`noremap <silent> <Leader>f :Fern . -drawer -reveal=% -toggle -width=35<CR><C-w>=`
`let g:fern#renderer = "nerdfont"`

Debugging further, I've isolated the issue to the `-reveal=%` part of my `<Leader> f` command.
Removing that option will prevent this bug from happening.

One more thing that I looked into:
I have this setting in vim:
`set autochdir`

Disabling this with my original two settings makes this bug much more difficult to reproduce, but it will eventually happen.

Steps to Reproduce:

1. `Leader f` to open
2. `Leader f` to close
3. `Leader f` to open again (crash)

Note: Pressing `Leader f` very quickly will *not* reproduce this bug. The presses need to happen with about 1 second in between.

On step 3, I do notice a new buffer:

![image](https://user-images.githubusercontent.com/8079338/92305038-62f78700-ef51-11ea-8dd1-e857d680f944.png)

I see this buffer open and close immediately when opening Fern. But on the crash, it remains there.

I have the following plugins installed:

`fern`
`fern-git-status`
`fern-mapping-git`
`fern-nerdfont`
`fern-renderer-nerdfont`
`fern-mapping-project-top`
`FixCursorHold.nvim`

**Comment by lambdalisue** [comment]
Write a **MINIMAL** vimrc first then write step by step procedure to reproduce the issue. Otherwise, it's not reproducible.

**Comment by Igor-Gold** [comment]
Sorry about that. I've debugged it further and isolated it to one plugin that was causing the problem:

[QuickScope](https://github.com/unblevable/quick-scope)

I don't think this issue is within the scope of this repository.
