### ISSUE TITLE
Support for nvim-web-devicons

### ISSUE THREAD

**Issue by Shatur** [lambdalisue/fern-renderer-nerdfont.vim#7]
Hi! There is another interesting project - [nvim-web-devicons](https://github.com/kyazdani42/nvim-web-devicons). Because of lua, it may be preferable to neovim users over nerdfont.vim. To avoid creating something like `fern-renderer-devicons.nvim` with almost the same code it may be better to integrate it here. What do you think?

**Comment by lambdalisue** [comment]
No. I think creating a particular plugin like `fern-renderer-nvim-web-devicons.nvim` or whatever is the **best** idea because

1. Code for supporting "nvim-web-devicons" is non required complexity for users who want a renderer of "nerdfont.vim"
2. Code for supporting "nerdfont.vim" is non required complexity for users who want a renderer of "nvim-web-devicons"

I'm sure that nobody wants bugs especially caused by non required complexity.

**Comment by Shatur** [comment]
Okay, thanks, will try to create a separate plugin.

**Comment by lambdalisue** [comment]
Thanks for understanding. Please add the plugin to https://github.com/lambdalisue/fern.vim/wiki/Plugins once you've succeeded :+1:

**Comment by Shatur** [comment]
Should I replace only [this](https://github.com/lambdalisue/fern-renderer-nerdfont.vim/blob/942be10bda577ba4840c4a939200f05024b8603c/autoload/fern/renderer/nerdfont.vim#L77) block and just copy all other code from this repo?

**Comment by lambdalisue** [comment]
Maybe. I've no idea the API of nvim-web-devicons though.

**Comment by Shatur** [comment]
The API is similar to nerdfont: just [a function to find icon](https://github.com/kyazdani42/nvim-web-devicons#get-icon). If I understand correctly, then only the above block is responsible for finding the icon. So, I will have a lot of duplicated code from this repo :(

**Comment by lambdalisue** [comment]
> If I understand correctly, then only the above block is responsible for finding the icon.

Right.

> So, I will have a lot of duplicated code from this repo :(

I think that's ideal while this and what you are going to make are completely different plugins 👍

**Comment by Shatur** [comment]
> I think that's ideal while this and what you are going to make are completely different plugins

But they will differ by only a few lines of code. I would suggest making one generic renderer for icons since all third party plugins for icons have almost the same API. It wouldn't add any performance overhead, but it would keep things like that in one place (I don't have to keep track of changes in this repository and merge all the improvements).

But I will okay if you disagree and create a separate plugin as we discussed before :)

**Comment by lambdalisue** [comment]
> since all third party plugins for icons have almost the same API

In my opinion, it's noted with "for now". I think all third-party plugins are not intrinsically equivalent thus APIs or usage may be different in the future. Then, I need to add extra glue code (extra complexity) which is not required if the plugin just has a single code for a single purpose.

I'm sorry for the inconvenience. But at least for now, I think we should make distinct plugins for distinct integrations while there are only three of them.

**Comment by Shatur** [comment]
> In my opinion, it's noted with "for now". I think all third-party plugins are not intrinsically equivalent thus APIs or usage may be different in the future. 

I can't even imagine how the API for getting icon can change. It always consists of one function. This plugin already have an abstraction under `s:find`, so it's easy to add support for other plugins.

> Then, I need to add extra glue code (extra complexity) which is not required if the plugin just has a single code for a single purpose.

This plugin also manages other things like highlighting and syntax that I have to copy and maintain according to this repo. Thus, instead of possible inconvenience in the future, we will have 100% inconvenience right now.

**Comment by lambdalisue** [comment]
It would be worth supporting both "nerdfont.vim" and "nvim-web-devicons" in a single repository for developers **but for users**. Additionally, it would be the extra non-necessary complexity while nobody uses "nerdfont.vim" and "nvim-web-devicons" at the same time.

**Comment by Shatur** [comment]
Plugins usually just provide an option to choose a provider, I don't see any problem for user with that...
But I got your point, I will create a separate plugin. I like `nerdfont.vim` a lot, `nvim-web-devicons` just better suit for Neovim because of lua.

**Comment by Trid-collab** [comment]
@Shatur Hi, did you finally get to make fern renderer with nvim-web-devicons. if so could you direct me to it. I would like to use it with my neovim nightly config

**Comment by Shatur** [comment]
> @Shatur Hi, did you finally get to make fern renderer with nvim-web-devicons. if so could you direct me to it. I would like to use it with my neovim nightly config

See https://github.com/lambdalisue/fern.vim/issues/359#issuecomment-895251149

**Comment by bluz71** [comment]
@Trid-collab,

See [this comment](https://github.com/lambdalisue/fern.vim/issues/359#issuecomment-896494570). I think the *fern_renderer_devicons* plugin could be extended with *nvim-web-devicons*; just a matter of changing a couple API calls.

**Comment by bluz71** [comment]
> See [this comment](https://github.com/lambdalisue/fern.vim/issues/359#issuecomment-896494570). I think the _fern_renderer_devicons_ plugin could be extended with _nvim-web-devicons_; just a matter of changing a couple API calls.

**Augmenting** API calls, not **changing**. Wrong wording. The [fern-renderer_devicons](https://github.com/lambdalisue/fern-renderer-devicons.vim) plugin could seamlessly support both *vim-devicons* and *nvim-web-devicons*.
