### ISSUE TITLE
About the Usage in README.md

### ISSUE THREAD

**Issue by nyngwang** [lambdalisue/fern-renderer-nerdfont.vim#9]
Is `nerdfont` the only option one can set by this plugin? Or it can be replaced by a font I've patched with nerd font?

    let g:fern#renderer = "nerdfont"

Thanks in advance.

**Comment by lambdalisue** [comment]
I'm sorry for the late reply. Well, the value `nerdfont` is the name of this renderer so it's a bit different from your font name.
